#!/bin/env bash

setxkbmap -layout fr -variant optimot_ansi_18 -option grp:alt_crt_toggle
# xset r rate 160 80
xset r rate 160 90
xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'
setxkbmap -option 'caps:ctrl_modifier'
xcape -e 'Caps_Lock=Escape'
