#!/usr//bin/env bash

# this script is used to fuzzy search directories on certain path and open them
# in vim

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/.coding/ ~/.coding/ALX/  ~/.ecole/ ~/.personal/ ~/.config/ -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

cd $selected
nvim .
