#!/bin/env bash

~/.config/natural-scrolling-and-tap/tap-to-click.sh
~/.config/natural-scrolling-and-tap/inverse-scroll.sh
setxkbmap -layout fr,de
xset r rate 130 70
xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'
# picom > /dev/null &
