#!/bin/env bash

~/.config/natural-scrolling-and-tap/tap-to-click.sh
~/.config/natural-scrolling-and-tap/inverse-scroll.sh
setxkbmap -layout fr,de
#setxkbmap -layout fr -variant optimot_ansi_18 -option grp:alt_crt_toggle
xset r rate 160 70
xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'
# picom > /dev/null &
