#!/bin/bash
# This script copy dotfiles to the repo location. In this case,
# ~/.coding/.dotfiles

app_list="cava dunst kitty nvim picom aliasrc neofetch qutebrowser rofi zathura scripts"

for app in $app_list; do
    cp -r ~/.config/"$app" ~/.coding/.dotfiles/.config/
done


# Copy zshrc
cp ~/.zshrc ~/.coding/.dotfiles/
