#!/bin/bash
# This script copy dotfiles to the repo location. In this case,
# ~/.coding/.dotfiles

app_list="cava dunst kitty nvim picom waybar sway aliasrc neofetch  rofi zathura scripts"

for app in $app_list; do
    cp -r ~/.config/"$app" ~/.coding/.dotfiles/.config/
done

# Copy zshrc
cp ~/.zshrc ~/.coding/.dotfiles/

# Copy tmux  config
cp ~/.tmux.conf ~/.coding/.dotfiles/
