#!/usr/bin/env bash
# This script copy dotfiles to the repo location. In this case,
# ~/.coding/.dotfiles

RED='\033[0;31m'
GREEN='\033[0;32m'

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

repo_path=~/.coding/.dotfiles
app_list="cava waypaper wob niri matugen fuzzel ghostty yazi dunst kitty waybar tmux sway swaylock aliasrc alacritty rofi zathura scripts hypr"

for app in $app_list; do
    cp -r ~/.config/"$app" ~/.coding/.dotfiles/.config/
done

# Copy zshrc
if cp -r ~/.zshrc $repo_path; then
    print_success "Configs copied successfully"
else
    print_error "Some forder does not exist anymore"
fi

# Copy gtk.css file

if cp -r ~/.config/gtk-3.0/gtk.css $repo_path/.config/gtk-3.0/; then
    print_success "GTK config copied successfully"
else
    print_error "GTK config does not exist anymore"
fi
if cp -r ~/.config/gtk-4.0/gtk.css $repo_path/.config/gtk-4.0/; then
    print_success "GTK config copied successfully"
else
    print_error "GTK config does not exist anymore"
fi
