[config]
reload_apps = true
# import_json_files = "~/.config/matugen/custom.json"

[templates.waybar]
input_path = "~/.config/waybar/template.css"
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.rofi]
input_path = '~/.config/rofi/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.dunst]
input_path = "~/.config/dunst/dunstrc.template"
output_path = "~/.config/dunst/dunstrc"

[templates.hyprland]
input_path = '~/.config/hypr/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.niri]
input_path = '~/.config/niri/niri-colors.kdl'
output_path = '~/.config/niri/colors.kdl'
post_hook = 'niri msg action load-config-file'

[templates.tmux]
input_path = '~/.config/tmux/tmux-colors.conf'
output_path = '~/.config/tmux/generated.conf'
post_hook = 'tmux source-file ~/.config/tmux/generated.conf'

[templates.zathura]
input_path = '~/.config/zathura/zathura-colors'
output_path = '~/.config/zathura/zathurarc'

[templates.alacritty]
input_path = '~/.config/alacritty/colors.toml'
output_path = '~/.config/alacritty/themes/colors.toml'

[templates.gtk3]
input_path = './gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
# post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'
# post_hook = '~/.config/scripts/gtk-toggle.sh'

[templates.gtk4]
input_path = './gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.qt5ct]
input_path = './qtct-colors.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6ct]
input_path = './qtct-colors.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'


[templates.sway]
input_path = '~/.config/sway/sway-colors.conf'
output_path = '~/.config/sway/colors.conf'
post_hook = 'swaymsg reload'

[templates.cava]
input_path = '~/.config/cava/cava-colors.ini'
output_path = '~/.config/cava/themes/sne'
post_hook = 'pkill -USR1 cava'

[templates.fuzzel]
input_path = '~/.config/fuzzel/fuzzel-colors.ini'
output_path = '~/.config/fuzzel/colors.ini'

[templates.neovim]
input_path = '~/.coding/nvim/lua/sne/colors-template.lua'
output_path = '~/.coding/nvim/lua/sne/colors.lua'
post_hook = 'pkill -SIGUSR1 nvim'

[templates.opencode]
input_path = '~/.config/opencode/themes/matugen-template.json'
output_path = '~/.config/opencode/themes/matugen.json'


